project:
  type: website
  output-dir: docs

website:
  title: "Diego A. Pacheco"
  site-url: https://dpacheco0921.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv.qmd
        text: CV
      - href: publications.qmd
        text: Publications
      - href: contact.qmd
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
